name: test
on: 
  push:
    branches:
      - main
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Main server
      run: sudo bash setup/main-setup.sh
    - name: Install Client Server
      run: sudo bash setup/client-setup.sh localhost
